# Generated by Django 4.2.2 on 2023-06-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='message',
            new_name='enquiry_details',
        ),
    ]
