# Generated by Django 4.1.7 on 2023-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_message_enquiry_enquiry_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='quotation_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
